In [1]:
import math
import sympy as sym
import numpy as np
import sys

In [2]:
# insert the matrix as array
A = np.array( [ [1, 1, 1, 3],
                [2, 3, 7, 0],
                [1, 3, -2, 17] ] )

print(A)

[[ 1  1  1  3]
 [ 2  3  7  0]
 [ 1  3 -2 17]]


In [3]:
d = 1
d2 = 2
i = 0
j = 0

while i < A.shape[0]:
    if A[i][i] == 0.0:
        sys.exit('Divide by zero detected!')

    # divide the entire row with the diagonal    
    A[i] = A[i]/A[i,i]
    print("Step", d)
    d = d + 2
    A[A == (-0)] = 0
    print(A)
    print("\n")
    for j in range(A.shape[0]):
        if j == i:
            continue
        A[j] = A[j] - A[j, i] * A[i]
        #j = j + 1
    print("Step", d2)
    d2 = d2 + 2
    print(A)
    print("\n")
    i = i + 1

Step 1
[[ 1  1  1  3]
 [ 2  3  7  0]
 [ 1  3 -2 17]]


Step 2
[[ 1  1  1  3]
 [ 0  1  5 -6]
 [ 0  2 -3 14]]


Step 3
[[ 1  1  1  3]
 [ 0  1  5 -6]
 [ 0  2 -3 14]]


Step 4
[[  1   0  -4   9]
 [  0   1   5  -6]
 [  0   0 -13  26]]


Step 5
[[ 1  0 -4  9]
 [ 0  1  5 -6]
 [ 0  0  1 -2]]


Step 6
[[ 1  0  0  1]
 [ 0  1  0  4]
 [ 0  0  1 -2]]




In [4]:
k = 0

while k < A.shape[0]:
    print("x[{}] = {}".format((k+1), A[k, -1]))
    k = k + 1

x[1] = 1
x[2] = 4
x[3] = -2
