In [1]:
import numpy as np
import sympy as sym

In [2]:
#num of column must be more than num of row
#column = row + 1

y = np.array( [ [-5., 0, 0, 0], 
                [-1, 3, 0, 0],
                [5, -3, 0, 0] ])
k = 1

print(y)

[[-5.  0.  0.  0.]
 [-1.  3.  0.  0.]
 [ 5. -3.  0.  0.]]


In [3]:
for j in range(y.shape[0] - 1):
    for i in range(y.shape[0] - 1):
        try:
            y[i][j+2] = ((y[i+1][j+1] - y[i][j+1]) / (y[i+k][0] - y[i][0]))
        except IndexError:
            continue
    k = k + 1
        
print(y)

[[-5.     0.     0.75  -0.175]
 [-1.     3.    -1.     0.   ]
 [ 5.    -3.     0.     0.   ]]


In [4]:
x = sym.Symbol('x')

equ = []
equ.append(str(y[0][1]))

for n in range(y.shape[0]):
    try:
        equ1 = y[0][n+2]*(x-y[0][0])
        if n >= 1:
            for i in range(n):
                equ1 = equ1*(x-y[i+1][0])
        equ.append(str(equ1))
    except IndexError:
        continue
    
print(equ)
equ = "+".join(equ)
fx = eval(equ)
sym.Eq(fx, 0)

['0.0', '0.75*x + 3.75', '(-0.175*x - 0.875)*(x + 1.0)']


Eq(0.75*x + (-0.175*x - 0.875)*(x + 1.0) + 3.75, 0)

In [5]:
# when x = a, get the value
a = 1.5

ans = fx.subs(x, a)
print(ans)

2.03125000000000
